### ISSUE TITLE
错误反馈: 服务器使用Docker部署，自定义容器ip，使用Nginx把3000端口映射到公网443，域名https访问报错

### ISSUE THREAD

**Issue by mapxn** [UNICKCHENG/openai-proxy#44]
### 能告诉我发生了什么么？What happened?

我的docker-compose.yaml文件
```yml
version: '3.9'
networks: 
  default:
    external: true
    name: npm_default

services:
  openai-proxy:
    image: unickcheng/openai-proxy:latest
    container_name: openai-proxy
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai

    networks:
      default:
        ipv4_address: 172.20.0.10
```
启动后, 服务正常运行在`http://172.20.0.10:3000`
在服务器端测试可以正常返回数据
```bash
curl -X POST 'http://172.20.0.10:3000/claude/b***c/v1/chat/completions' \
--header 'Accept: */*' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer sk-ant-***' \
--data-raw '{
    "model":"gpt-3.5-turbo",
    "messages": [
        {"role": "user", "content":"hello"}
    ],
    "stream": false
}'
```
<img width="1541" alt="image" src="https://github.com/UNICKCHENG/openai-proxy/assets/16299874/1d1e6c8e-c841-4d1d-870e-65b851bb652c">

在服务端使用Nginx proxy manager 把 `http://172.20.0.10:3000` 反向代理到443端口，启用https+绑定域名

本地 **使用https://域名** 方式，报错了：

**CURL返回数据为空，使用-v参数返回代码500**
```
< HTTP/2 500
< date: Thu, 10 Aug 2023 12:00:51 GMT
< content-length: 0
< access-control-allow-headers: Content-Type, Accept, Authorization
< access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
< access-control-allow-origin: *
< vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Url
< strict-transport-security: max-age=63072000;includeSubDomains; preload
< cf-cache-status: DYNAMIC
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=******"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 7f4814accd52af43-NRT
< alt-svc: h3=":443"; ma=86400
```
去服务器端查看docker日志：

```
- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- error TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: [Error: 98CBF5449C7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  ] {
    library: 'SSL routines',
    reason: 'wrong version number',
    code: 'ERR_SSL_WRONG_VERSION_NUMBER'
  }
}
```

在本地测试 **使用http**，却可正常返回数据
 
<img width="1014" alt="image" src="https://github.com/UNICKCHENG/openai-proxy/assets/16299874/b6c83625-8e61-481b-bc50-667fe6b945f8">

请问如何使用https访问接口？是Nginx配置有问题吗？
<img width="500" alt="image" src="https://github.com/UNICKCHENG/openai-proxy/assets/16299874/65cf99fc-50ad-4247-ac4d-bf82c7f2dd3e">
